### PR TITLE
Perform CI over Erlang 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by lrascao** [comment]
It has been decided (by higher instances) that for security reasons we don't want to keep this repo public.

**Comment by paulo-ferraz-oliveira** [comment]
Well, even if the repo is private it doesn't mean that CI can't run, right?

**Comment by lrascao** [comment]
Won't even be private, will just live in our internal repo

**Comment by paulo-ferraz-oliveira** [comment]
I've deleted my fork of it, in any case.

**Pull request closed without merging**
